version: "3.9"
services:
  cassandra:
    image: cassandra:latest
    container_name: wsu415_cassandra
    networks:
      - wsu415
    volumes:
      - ./cassandra_data/cassandra:/var/lib/cassandra
    ports:
      - 9042:9042
  gui:
    image: ipushc/cassandra-web
    container_name: wsu415_gui
    restart: on-failure
    networks:
      - wsu415
    ports:
      - 9043:8083
    environment:
      - CASSANDRA_PORT=9042
    depends_on:
      - cassandra

networks:
  wsu415: